name: Build Sphinx Documentation

on:
  push:
    branches:
    - master
    - gh-workflow-sphinx-build
  pull_request:
    branches:
    - master

jobs:
  docs:
    name: Building sphinx documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build html docs
      run: |
        ls sphinx